# version: '3'
# services:
#   mysql:
#     image: mysql:5.6.27
#     ports:
#       - "127.0.0.1:3306:3306"
#     volumes:
#       - mysqldata:/var/lib/mysql
#       - ./initdb:/docker-entrypoint-initdb.d  
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: Gn1d0c@123
#       TZ: Asia/Kolkata

# volumes:
#   mysqldata:
#     driver: local

version: '3.8'

services:
  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gn1d0c@123
    ports:
      - "3306:3306"
